
package org.lmn.laserRaster
{
	public class LaserConfiguration
	{
		public var RESOLUTION:Number = 0.2;  //X and Y Stepover Resolution
		public var SPEED:Number = 10;  //X and Y Stepover Resolution
		public var MAXPOWER:Number = 60;  //X and Y Stepover Resolution
		public var MINPOWER:Number = 0;  //X and Y Stepover Resolution
		public var STARTX:Number = 50;  //X Start Position
		public var STARTY:Number = 50;  //Y Start Position
		

		public function newData(newResolution:Number, newSpeed:Number, maxPower:Number, minPower:Number, newStartx:Number, newStarty:Number):void
		{
			RESOLUTION = newResolution;
			
			if (newSpeed > 180) 
			{
				newSpeed = 180;
			}
			if (maxPower > 100) 
			{
				maxPower = 100;
			}
			if (minPower >= maxPower) 
			{
				minPower = maxPower - 1;
			}
			SPEED = newSpeed;
			MAXPOWER = maxPower;
			MINPOWER = minPower;
			RES = newResolution;
			SPD = newSpeed;
			PMAX = maxPower;
			PMIN = minPower;
			STARTX = newStartx;
			STARTY = newStarty;
			XOFF = newStartx;
			YOFF = newStarty;
		}

		public function get newResolutionMM():Number
		{
			return RESOLUTION;
		}
		
		public function get newSpeedP():Number
		{
			return SPEED;
		}
		
		public function get maxPowerP():Number
		{
			return MAXPOWER;
		}
		
		public function get minPowerP():Number
		{
			return MINPOWER;
		}
		
		public function get newStartxP():Number
		{
			return STARTX;
		}
		
		public function get newStartyP():Number
		{
			return STARTY;
		}
		
		public static const PREAMBLE:String =";(Generated by Image2Gcode Post Processor GLSRI02)\r\n" +
			";(Start code)\r\n" +	
			"M12\r\n" +
			"G90\r\n" +
			"M6 T3\r\n" +
			"M7 S0\r\n" +
			"M3\r\n" +
			"M38 S191\r\n" +
			"M36\r\n" +
			"G4 P5000\r\n"

		public static const POSTAMBLE:String = ";(End code)\r\n" +
			"M7 S0\r\n" +
			"M37\r\n" +
			"M5\r\n" +
			"M38 S0\r\n" +
			"M2\r\n"

		
		public static var RES:Number = new Number(0.2);  //X and Y Stepover Resolution
		public static const PPMM:Number = 1 / RES;  //Pixels per Millimeter
		public static const PPI:Number = PPMM * 0.0393701;  //Pixels per Inch

		public static var PMAX:Number = new Number(60); //Maximum power percent
		public static var PMIN:Number = new Number(0); //Minimum power percent
		public static var SPD:Number = new Number(10); //Millimeters per Minute
		public static var XOFF:Number = new Number(0); //X Offset
		public static var YOFF:Number = new Number(0); //Y Offset

		public function LaserConfiguration()
		{
		}
	}
}
